INSERT INTO states (STATE, NAME) VALUES 
 ('AA','Armed Forces Americas (except Canada)'),
 ('AE','Armed Forces Middle East'),
 ('AK','ALASKA'),
 ('AL','ALABAMA'),
 ('AP','Armed Forces Pacific'),
 ('AR','ARKANSAS'),
 ('AS','AMERICAN SAMOA'),
 ('AZ','ARIZONA'),
 ('CA','CALIFORNIA'),
 ('CO','COLORADO'),
 ('CT','CONNECTICUT'),
 ('DC','DISTRICT OF COLUMBIA'),
 ('DE','DELAWARE'),
 ('FL','FLORIDA'),
 ('FM','FEDERATED STATES OF MICRONESI'),
 ('GA','GEORGIA'),
 ('GU','GUAM'),
 ('HI','HAWAII'),
 ('IA','IOWA'),
 ('ID','IDAHO'),
 ('IL','ILLINOIS'),
 ('IN','INDIANA'),
 ('KS','KANSAS'),
 ('KY','KENTUCKY'),
 ('LA','LOUISIANA'),
 ('MA','MASSACHUSETTS'),
 ('MD','MARYLAND'),
 ('ME','MAINE'),
 ('MH','MARSHALL ISLANDS'),
 ('MI','MICHIGAN'),
 ('MN','MINNESOTA'),
 ('MO','MISSOURI'),
 ('MP','NORTHERN MARIANA ISLANDS'),
 ('MS','MISSISSIPPI'),
 ('MT','MONTANA'),
 ('NC','NORTH CAROLINA'),
 ('ND','NORTH DAKOTA'),
 ('NE','NEBRASKA'),
 ('NH','NEW HAMPSHIRE'),
 ('NJ','NEW JERSEY'),
 ('NM','NEW MEXICO'),
 ('NV','NEVADA'),
 ('NY','NEW YORK'),
 ('OH','OHIO'),
 ('OK','OKLAHOMA'),
 ('OR','OREGON'),
 ('PA','PENNSYLVANIA'),
 ('PR','PUERTO RICO'),
 ('PW','PALAU'),
 ('RI','RHODE ISLAND'),
 ('SC','SOUTH CAROLINA'),
 ('SD','SOUTH DAKOTA'),
 ('TN','TENNESSEE'),
 ('TX','TEXAS'),
 ('UT','UTAH'),
 ('VA','VIRGINIA'),
 ('VI','VIRGIN ISLANDS'),
 ('VT','VERMONT'),
 ('WA','WASHINGTON'),
 ('WI','WISCONSIN'),
 ('WV','WEST VIRGINIA'),
 ('WY','WYOMING');